title: Bava Docs
description: Tutorials and Engineering Materials
theme: just-the-docs

url: https://bavadg8.github.io/suvedha-docs

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://github.com/bavagd8/suvedha-docs
