title: Suvedha Docs
description: Mojo V3, FPGA tutorials, and notes
theme: just-the-docs

# Optional but recommended:
url: https://bavadg8.github.io
baseurl: /suvedha-docs # <-- only if your repo is NOT named bavadg8.github.io

# Enable search
search_enabled: true

gem "just-the-docs"

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

